# A generic, single database configuration.

[alembic]
# path to migration script
script_location = backend/migrations

# template used to generate migration file names; The default value is %%(rev)s_%%(slug)s
# file_template = %%(rev)s_%%(slug)s

# sys.path path, will be prepended to sys.path if present.
prepend_sys_path = . backend
path_separator = os

# timezone to use when rendering the date within the migration file
# timezone =

# max length of characters which will be used to make the "slug" field
# truncate_slug_length = 40

# set to 'true' to run the environment during
# the 'revision' command, regardless of autogenerate
# revision_environment = false

# set to 'true' to allow .pyc and .pyo files without
# a source .py file to be detected as revisions in the
# versions/ directory
# sourceless = false

# version location specification; This defaults to backend/migrations/versions.
version_locations = backend/migrations/versions

# set to 'true' to search source files recursively in each chain.
# recursive_version_locations = false

# output encoding used when --template is supplied
# output_encoding = utf-8

sqlalchemy.url = sqlite:///data/database.db


[post_write_hooks]

[logging]
default_handler_name = console

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
