"""001_initial_schema_22_tables: deterministic Alembic schema snapshot."""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = 'e822fa83c9db'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
        op.create_table('model_versions',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('model_name', sa.String(length=100), nullable=False),
        sa.Column('version', sa.String(length=50), nullable=False),
        sa.Column('task_type', sa.String(length=50), nullable=False),
        sa.Column('weights_path', sa.String(length=500), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('deployed_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_model_versions_model_name'), 'model_versions', ['model_name'], unique=False)
        op.create_table('plants',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('code', sa.String(length=50), nullable=False),
        sa.Column('location', sa.String(length=255), nullable=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_plants_code'), 'plants', ['code'], unique=True)
        op.create_table('roles',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('name', sa.String(length=50), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('permissions_json', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
        op.create_table('areas',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('plant_id', sa.String(length=36), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('code', sa.String(length=50), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_areas_code'), 'areas', ['code'], unique=False)
        op.create_index(op.f('ix_areas_plant_id'), 'areas', ['plant_id'], unique=False)
        op.create_table('model_metrics',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('model_version_id', sa.String(length=36), nullable=False),
        sa.Column('dataset_name', sa.String(length=100), nullable=False),
        sa.Column('precision', sa.Float(), nullable=True),
        sa.Column('recall', sa.Float(), nullable=True),
        sa.Column('f1_score', sa.Float(), nullable=True),
        sa.Column('map50', sa.Float(), nullable=True),
        sa.Column('fps', sa.Float(), nullable=True),
        sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('is_igl_validated', sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_model_metrics_model_version_id'), 'model_metrics', ['model_version_id'], unique=False)
        op.create_table('users',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('role_id', sa.String(length=36), nullable=True),
        sa.Column('username', sa.String(length=100), nullable=False),
        sa.Column('email', sa.String(length=255), nullable=False),
        sa.Column('hashed_password', sa.String(length=255), nullable=False),
        sa.Column('full_name', sa.String(length=150), nullable=False),
        sa.Column('employee_code', sa.String(length=50), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
        op.create_index(op.f('ix_users_employee_code'), 'users', ['employee_code'], unique=False)
        op.create_index(op.f('ix_users_role_id'), 'users', ['role_id'], unique=False)
        op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
        op.create_table('audit_logs',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('user_id', sa.String(length=36), nullable=True),
        sa.Column('action', sa.String(length=100), nullable=False),
        sa.Column('resource_type', sa.String(length=50), nullable=False),
        sa.Column('resource_id', sa.String(length=36), nullable=True),
        sa.Column('details_json', sa.JSON(), nullable=True),
        sa.Column('ip_address', sa.String(length=45), nullable=True),
        sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
        op.create_index(op.f('ix_audit_logs_resource_type'), 'audit_logs', ['resource_type'], unique=False)
        op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
        op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
        op.create_table('zones',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('area_id', sa.String(length=36), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('code', sa.String(length=50), nullable=False),
        sa.Column('zone_type', sa.String(length=50), nullable=False),
        sa.Column('geometry_json', sa.JSON(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_zones_area_id'), 'zones', ['area_id'], unique=False)
        op.create_index(op.f('ix_zones_code'), 'zones', ['code'], unique=False)
        op.create_table('cameras',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('zone_id', sa.String(length=36), nullable=True),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('code', sa.String(length=50), nullable=False),
        sa.Column('stream_url', sa.String(length=500), nullable=False),
        sa.Column('camera_type', sa.String(length=50), nullable=False),
        sa.Column('fps', sa.Float(), nullable=False),
        sa.Column('resolution', sa.String(length=20), nullable=False),
        sa.Column('location_description', sa.Text(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_cameras_code'), 'cameras', ['code'], unique=True)
        op.create_index(op.f('ix_cameras_zone_id'), 'cameras', ['zone_id'], unique=False)
        op.create_table('equipments',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('zone_id', sa.String(length=36), nullable=True),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('equipment_type', sa.String(length=50), nullable=False),
        sa.Column('serial_number', sa.String(length=100), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_equipments_zone_id'), 'equipments', ['zone_id'], unique=False)
        op.create_table('ppe_rules',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('zone_id', sa.String(length=36), nullable=True),
        sa.Column('ppe_type', sa.String(length=50), nullable=False),
        sa.Column('is_mandatory', sa.Boolean(), nullable=False),
        sa.Column('min_confidence', sa.Float(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_ppe_rules_zone_id'), 'ppe_rules', ['zone_id'], unique=False)
        op.create_table('camera_health',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('camera_id', sa.String(length=36), nullable=False),
        sa.Column('status', sa.String(length=50), nullable=False),
        sa.Column('last_frame_timestamp', sa.DateTime(timezone=True), nullable=True),
        sa.Column('fps', sa.Float(), nullable=False),
        sa.Column('latency_ms', sa.Float(), nullable=False),
        sa.Column('is_frozen', sa.Boolean(), nullable=False),
        sa.Column('is_black', sa.Boolean(), nullable=False),
        sa.Column('image_quality_score', sa.Float(), nullable=False),
        sa.Column('inference_status', sa.String(length=50), nullable=False),
        sa.Column('health_timestamp', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_camera_health_camera_id'), 'camera_health', ['camera_id'], unique=True)
        op.create_table('tracks',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('camera_id', sa.String(length=36), nullable=False),
        sa.Column('track_uuid', sa.String(length=100), nullable=False),
        sa.Column('object_class', sa.String(length=50), nullable=False),
        sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('employee_id', sa.String(length=36), nullable=True),
        sa.Column('metadata_json', sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['employee_id'], ['users.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_tracks_camera_id'), 'tracks', ['camera_id'], unique=False)
        op.create_index(op.f('ix_tracks_employee_id'), 'tracks', ['employee_id'], unique=False)
        op.create_index(op.f('ix_tracks_track_uuid'), 'tracks', ['track_uuid'], unique=False)
        op.create_table('detections',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('camera_id', sa.String(length=36), nullable=False),
        sa.Column('track_id', sa.String(length=36), nullable=True),
        sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
        sa.Column('object_class', sa.String(length=50), nullable=False),
        sa.Column('confidence', sa.Float(), nullable=False),
        sa.Column('bbox_json', sa.JSON(), nullable=False),
        sa.Column('observation_state', sa.String(length=50), nullable=False),
        sa.Column('metadata_json', sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_detections_camera_id'), 'detections', ['camera_id'], unique=False)
        op.create_index(op.f('ix_detections_timestamp'), 'detections', ['timestamp'], unique=False)
        op.create_index(op.f('ix_detections_track_id'), 'detections', ['track_id'], unique=False)
        op.create_table('events',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('camera_id', sa.String(length=36), nullable=False),
        sa.Column('zone_id', sa.String(length=36), nullable=True),
        sa.Column('track_id', sa.String(length=36), nullable=True),
        sa.Column('event_type', sa.String(length=100), nullable=False),
        sa.Column('observation_state', sa.String(length=50), nullable=False),
        sa.Column('severity', sa.String(length=20), nullable=False),
        sa.Column('workflow_state', sa.String(length=50), nullable=False),
        sa.Column('confidence', sa.Float(), nullable=False),
        sa.Column('duration_seconds', sa.Float(), nullable=False),
        sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('model_version', sa.String(length=50), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_events_camera_id'), 'events', ['camera_id'], unique=False)
        op.create_index(op.f('ix_events_event_type'), 'events', ['event_type'], unique=False)
        op.create_index(op.f('ix_events_severity'), 'events', ['severity'], unique=False)
        op.create_index(op.f('ix_events_started_at'), 'events', ['started_at'], unique=False)
        op.create_index(op.f('ix_events_track_id'), 'events', ['track_id'], unique=False)
        op.create_index(op.f('ix_events_workflow_state'), 'events', ['workflow_state'], unique=False)
        op.create_index(op.f('ix_events_zone_id'), 'events', ['zone_id'], unique=False)
        op.create_table('acknowledgements',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('event_id', sa.String(length=36), nullable=False),
        sa.Column('user_id', sa.String(length=36), nullable=False),
        sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_acknowledgements_event_id'), 'acknowledgements', ['event_id'], unique=False)
        op.create_index(op.f('ix_acknowledgements_user_id'), 'acknowledgements', ['user_id'], unique=False)
        op.create_table('assignments',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('event_id', sa.String(length=36), nullable=False),
        sa.Column('assigned_to_user_id', sa.String(length=36), nullable=False),
        sa.Column('assigned_by_user_id', sa.String(length=36), nullable=True),
        sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(['assigned_by_user_id'], ['users.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['assigned_to_user_id'], ['users.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_assignments_assigned_to_user_id'), 'assignments', ['assigned_to_user_id'], unique=False)
        op.create_index(op.f('ix_assignments_event_id'), 'assignments', ['event_id'], unique=False)
        op.create_table('event_evidence',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('event_id', sa.String(length=36), nullable=False),
        sa.Column('evidence_type', sa.String(length=50), nullable=False),
        sa.Column('file_path', sa.String(length=500), nullable=False),
        sa.Column('file_hash', sa.String(length=64), nullable=True),
        sa.Column('thumbnail_path', sa.String(length=500), nullable=True),
        sa.Column('metadata_json', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_event_evidence_event_id'), 'event_evidence', ['event_id'], unique=False)
        op.create_table('incidents',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('event_id', sa.String(length=36), nullable=True),
        sa.Column('title', sa.String(length=255), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('severity', sa.String(length=20), nullable=False),
        sa.Column('status', sa.String(length=50), nullable=False),
        sa.Column('reported_by_user_id', sa.String(length=36), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['reported_by_user_id'], ['users.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_incidents_event_id'), 'incidents', ['event_id'], unique=False)
        op.create_table('near_misses',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('event_id', sa.String(length=36), nullable=True),
        sa.Column('title', sa.String(length=255), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('potential_severity', sa.String(length=20), nullable=False),
        sa.Column('interaction_type', sa.String(length=100), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_near_misses_event_id'), 'near_misses', ['event_id'], unique=False)
        op.create_table('notifications',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('event_id', sa.String(length=36), nullable=True),
        sa.Column('user_id', sa.String(length=36), nullable=False),
        sa.Column('channel', sa.String(length=50), nullable=False),
        sa.Column('recipient', sa.String(length=255), nullable=True),
        sa.Column('status', sa.String(length=50), nullable=False),
        sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_notifications_event_id'), 'notifications', ['event_id'], unique=False)
        op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
        op.create_table('corrective_actions',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('event_id', sa.String(length=36), nullable=True),
        sa.Column('incident_id', sa.String(length=36), nullable=True),
        sa.Column('near_miss_id', sa.String(length=36), nullable=True),
        sa.Column('action_description', sa.Text(), nullable=False),
        sa.Column('assigned_to_user_id', sa.String(length=36), nullable=True),
        sa.Column('status', sa.String(length=50), nullable=False),
        sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
        sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['assigned_to_user_id'], ['users.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['near_miss_id'], ['near_misses.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_corrective_actions_assigned_to_user_id'), 'corrective_actions', ['assigned_to_user_id'], unique=False)
        op.create_index(op.f('ix_corrective_actions_event_id'), 'corrective_actions', ['event_id'], unique=False)
        op.create_index(op.f('ix_corrective_actions_incident_id'), 'corrective_actions', ['incident_id'], unique=False)
        op.create_index(op.f('ix_corrective_actions_near_miss_id'), 'corrective_actions', ['near_miss_id'], unique=False)
        # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
        op.drop_index(op.f('ix_corrective_actions_near_miss_id'), table_name='corrective_actions')
        op.drop_index(op.f('ix_corrective_actions_incident_id'), table_name='corrective_actions')
        op.drop_index(op.f('ix_corrective_actions_event_id'), table_name='corrective_actions')
        op.drop_index(op.f('ix_corrective_actions_assigned_to_user_id'), table_name='corrective_actions')
        op.drop_table('corrective_actions')
        op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
        op.drop_index(op.f('ix_notifications_event_id'), table_name='notifications')
        op.drop_table('notifications')
        op.drop_index(op.f('ix_near_misses_event_id'), table_name='near_misses')
        op.drop_table('near_misses')
        op.drop_index(op.f('ix_incidents_event_id'), table_name='incidents')
        op.drop_table('incidents')
        op.drop_index(op.f('ix_event_evidence_event_id'), table_name='event_evidence')
        op.drop_table('event_evidence')
        op.drop_index(op.f('ix_assignments_event_id'), table_name='assignments')
        op.drop_index(op.f('ix_assignments_assigned_to_user_id'), table_name='assignments')
        op.drop_table('assignments')
        op.drop_index(op.f('ix_acknowledgements_user_id'), table_name='acknowledgements')
        op.drop_index(op.f('ix_acknowledgements_event_id'), table_name='acknowledgements')
        op.drop_table('acknowledgements')
        op.drop_index(op.f('ix_events_zone_id'), table_name='events')
        op.drop_index(op.f('ix_events_workflow_state'), table_name='events')
        op.drop_index(op.f('ix_events_track_id'), table_name='events')
        op.drop_index(op.f('ix_events_started_at'), table_name='events')
        op.drop_index(op.f('ix_events_severity'), table_name='events')
        op.drop_index(op.f('ix_events_event_type'), table_name='events')
        op.drop_index(op.f('ix_events_camera_id'), table_name='events')
        op.drop_table('events')
        op.drop_index(op.f('ix_detections_track_id'), table_name='detections')
        op.drop_index(op.f('ix_detections_timestamp'), table_name='detections')
        op.drop_index(op.f('ix_detections_camera_id'), table_name='detections')
        op.drop_table('detections')
        op.drop_index(op.f('ix_tracks_track_uuid'), table_name='tracks')
        op.drop_index(op.f('ix_tracks_employee_id'), table_name='tracks')
        op.drop_index(op.f('ix_tracks_camera_id'), table_name='tracks')
        op.drop_table('tracks')
        op.drop_index(op.f('ix_camera_health_camera_id'), table_name='camera_health')
        op.drop_table('camera_health')
        op.drop_index(op.f('ix_ppe_rules_zone_id'), table_name='ppe_rules')
        op.drop_table('ppe_rules')
        op.drop_index(op.f('ix_equipments_zone_id'), table_name='equipments')
        op.drop_table('equipments')
        op.drop_index(op.f('ix_cameras_zone_id'), table_name='cameras')
        op.drop_index(op.f('ix_cameras_code'), table_name='cameras')
        op.drop_table('cameras')
        op.drop_index(op.f('ix_zones_code'), table_name='zones')
        op.drop_index(op.f('ix_zones_area_id'), table_name='zones')
        op.drop_table('zones')
        op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
        op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
        op.drop_index(op.f('ix_audit_logs_resource_type'), table_name='audit_logs')
        op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
        op.drop_table('audit_logs')
        op.drop_index(op.f('ix_users_username'), table_name='users')
        op.drop_index(op.f('ix_users_role_id'), table_name='users')
        op.drop_index(op.f('ix_users_employee_code'), table_name='users')
        op.drop_index(op.f('ix_users_email'), table_name='users')
        op.drop_table('users')
        op.drop_index(op.f('ix_model_metrics_model_version_id'), table_name='model_metrics')
        op.drop_table('model_metrics')
        op.drop_index(op.f('ix_areas_plant_id'), table_name='areas')
        op.drop_index(op.f('ix_areas_code'), table_name='areas')
        op.drop_table('areas')
        op.drop_index(op.f('ix_roles_name'), table_name='roles')
        op.drop_table('roles')
        op.drop_index(op.f('ix_plants_code'), table_name='plants')
        op.drop_table('plants')
        op.drop_index(op.f('ix_model_versions_model_name'), table_name='model_versions')
        op.drop_table('model_versions')
        # ### end Alembic commands ###